install.packages(c('devtools'),  repos='https://ftp.acc.umu.se/mirror/CRAN/')
library(devtools)
source("https://bioconductor.org/biocLite.R")
biocLite()
install_github('RGLab/MAST')
install_github('stela2502/RFclust.SGE')
install()
